[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1

board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_qspi
;board_build.partitions = huge_app_littlefs.csv

build_flags =
	${common.build_flags}

lib_deps = 
	${common.lib_deps}
